[[index]]
index_name = "yummy-index"
time = "0 * 9-23 * * * *"
indexing_type = "dynamic"
function_name = "store_dynamic_index"
sql_batch_size = 100
es_batch_size = 100


[[index]]
index_name = "yummy-index"
time = "0 30 8 * * * *"
indexing_type = "static"
setting_path = "./indexing_settings/store_infos.json"
function_name = "store_static_index"
sql_batch_size = 100
es_batch_size = 100
