//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub mod prelude;

pub mod elastic_index_info_tbl;
pub mod migrations;
pub mod recommend_tbl;
pub mod store;
pub mod store_backup;
pub mod store_location_info_tbl;
pub mod store_old;
pub mod store_recommend_tbl;
pub mod users;
pub mod zero_possible_market;
pub mod zero_possible_market_backup;
