//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

use crate::entity::recommend_tbl;
use crate::entity::store_recommend_tbl;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "recommend_tbl")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub recommend_seq: i32,
    pub recommend_name: String,
    pub recommend_yn: String,
    pub reg_dt: DateTime,
    pub chg_dt: Option<DateTime>,
    pub reg_id: String,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::store_recommend_tbl::Entity")]
    StoreRecommendTbl,
}

impl Related<store_recommend_tbl::Entity> for recommend_tbl::Entity {
    fn to() -> RelationDef {
        Relation::StoreRecommendTbl.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
