//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

use crate::entity::recommend_tbl;
use crate::entity::store;
use crate::entity::store_recommend_tbl;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "store_recommend_tbl")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommend_seq: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub seq: i32,
    pub recommend_end_dt: DateTime,
    pub reg_dt: DateTime,
    pub chg_dt: Option<DateTime>,
    pub reg_id: String,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::store::Entity",
        from = "Column::Seq",
        to = "super::store::Column::Seq"
    )]
    Store,
    #[sea_orm(
        belongs_to = "super::recommend_tbl::Entity",
        from = "Column::RecommendSeq",
        to = "super::recommend_tbl::Column::RecommendSeq"
    )]
    RecommendTbl,
}

impl Related<store::Entity> for store_recommend_tbl::Entity {
    fn to() -> RelationDef {
        Relation::Store.def()
    }
}

impl Related<recommend_tbl::Entity> for store_recommend_tbl::Entity {
    fn to() -> RelationDef {
        Relation::RecommendTbl.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
