//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

use crate::entity::store;
use crate::entity::zero_possible_market;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "zero_possible_market")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub seq: i32,
    pub use_yn: String,
    pub name: String,
    pub reg_dt: Option<DateTime>,
    pub chg_dt: Option<DateTime>,
    pub reg_id: Option<String>,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::store::Entity",
        from = "Column::Seq",
        to = "super::store::Column::Seq"
    )]
    Store,
}

impl Related<store::Entity> for zero_possible_market::Entity {
    fn to() -> RelationDef {
        Relation::Store.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
